[package]
name = "pos"
version = "0.1.0"
authors = ["Niklas Gustavsson <niklas@protocol7.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["staticlib"]

[dependencies]
linked_list_allocator = "0.6.4"
